
/*
 * Created on 26 oct. 2014 ( Time 19:52:14 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package eventmanager.business.mock;

import java.util.LinkedList;
import java.util.List;

import eventmanager.business.bean.jpa.ParticipantsEntity;
import eventmanager.business.mock.tool.MockValues;

public class ParticipantsEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ParticipantsEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ParticipantsEntity createInstance( Integer id ) {
		ParticipantsEntity entity = new ParticipantsEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setNom( mockValues.nextString(12) ) ; // java.lang.String 
		entity.setPrenom( mockValues.nextString(12) ) ; // java.lang.String 
		entity.setEmail( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setSociete( mockValues.nextString(24) ) ; // java.lang.String 
		// Init Link fields (if any)
		EventsEntityMock eventMock = new EventsEntityMock();
		entity.setListOfEvents(eventMock.createList(1));
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ParticipantsEntity> createList(int count) {
		List<ParticipantsEntity> list = new LinkedList<ParticipantsEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
