
/*
 * Created on 26 oct. 2014 ( Time 19:52:14 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package eventmanager.business.mock;

import java.util.LinkedList;
import java.util.List;

import eventmanager.business.bean.jpa.RegistrationEntity;
import eventmanager.business.mock.tool.MockValues;

public class RegistrationEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public RegistrationEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger(), mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public RegistrationEntity createInstance( Integer idevent, Integer idparticipant ) {
		RegistrationEntity entity = new RegistrationEntity();
		// Init Primary Key fields
		entity.setIdevent( idevent) ;
		entity.setIdparticipant( idparticipant) ;
		// Init Data fields
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<RegistrationEntity> createList(int count) {
		List<RegistrationEntity> list = new LinkedList<RegistrationEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
