/*
 * Created on 27 oct. 2014 ( Time 17:22:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package eventmanager.test.persistence;


import org.junit.Assert;
import org.junit.Test;

import eventmanager.business.bean.jpa.RegistrationEntity;
import eventmanager.business.mock.RegistrationEntityMock;
import eventmanager.business.persistence.PersistenceServiceProvider;
import eventmanager.business.persistence.services.RegistrationPersistence;

/**
 * JUnit test case for Registration persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class RegistrationPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		RegistrationPersistence service = PersistenceServiceProvider.getService(RegistrationPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Registration persistence : delete + load ..." );
		
		RegistrationPersistence service = PersistenceServiceProvider.getService(RegistrationPersistence.class);
		
		RegistrationEntityMock mock = new RegistrationEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 , 0  );
		// process( service, mock, ... );
	}

	private void process(RegistrationPersistence service, RegistrationEntityMock mock, Integer idevent, Integer idparticipant ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		RegistrationEntity entity = service.load( idevent, idparticipant );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( idevent, idparticipant ) ;
			Assert.assertNotNull(entity);

			/* NB : this entity is a "Join Table" 
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( idevent, idparticipant );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
