/*
 * Created on 26 oct. 2014 ( Time 19:52:14 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package eventmanager.business.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import eventmanager.business.bean.jpa.RegistrationEntity;
import eventmanager.business.bean.jpa.RegistrationEntityKey;
import eventmanager.business.persistence.commons.jpa.GenericJpaService;
import eventmanager.business.persistence.commons.jpa.JpaOperation;
import eventmanager.business.persistence.services.RegistrationPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Registration" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class RegistrationPersistenceJPA extends GenericJpaService<RegistrationEntity, RegistrationEntityKey> implements RegistrationPersistence {

	/**
	 * Constructor
	 */
	public RegistrationPersistenceJPA() {
		super(RegistrationEntity.class);
	}

	@Override
	public RegistrationEntity load( Integer idevent, Integer idparticipant ) {
		// Build the composite key
		RegistrationEntityKey key = new RegistrationEntityKey( idevent, idparticipant );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer idevent, Integer idparticipant ) {
		// Build the composite key
		RegistrationEntityKey key = new RegistrationEntityKey( idevent, idparticipant );
		return super.delete( key );
	}

	@Override
	public boolean delete(RegistrationEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			RegistrationEntityKey key = new RegistrationEntityKey( entity.getIdevent(), entity.getIdparticipant() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("RegistrationEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
