/*
 * Created on 26 oct. 2014 ( Time 19:52:14 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package eventmanager.business.persistence.services;

import java.util.List;
import java.util.Map;

import eventmanager.business.bean.jpa.RegistrationEntity;

/**
 * Basic persistence operations for entity "Registration"
 * 
 * This Bean has a composite Primary Key : RegistrationEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface RegistrationPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param registration
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(RegistrationEntity registration) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idevent
	 * @param idparticipant
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idevent, Integer idparticipant) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param registration
	 */
	public void insert(RegistrationEntity registration) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idevent
	 * @param idparticipant
	 * @return the entity loaded (or null if not found)
	 */
	public RegistrationEntity load(Integer idevent, Integer idparticipant) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<RegistrationEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<RegistrationEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<RegistrationEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param registration
	 * @return
	 */
	public RegistrationEntity save(RegistrationEntity registration) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<RegistrationEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
